include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - 'lib/**/*.chopper.dart'
    - 'lib/**/*.swagger.dart'
    - 'lib/**/*.g.dart'

linter:
  rules:
    sort_pub_dependencies: false
    avoid_dynamic_calls: true
    invariant_booleans: true
    require_trailing_commas: true