name: mxc_logic
description: MXC shared logic library
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  chopper: ^4.0.5
  decimal: ^2.2.0
  meta: ^1.7.0
  path: ^1.8.0
  sembast: ^3.1.0+2
  sembast_web: ^2.0.0+2
  collection: ^1.15.0
  http: ^0.13.4
  rxdart: ^0.27.3

dev_dependencies:
  analyzer: ^3.0.0
  flutter_lints: ^2.0.1
  test: ^1.16.0
  dotenv: ^3.0.0
  
  chopper_generator: ^4.0.5
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  swagger_dart_code_generator: 
    git: https://github.com/festelo/swagger-dart-code-generator.git
  build_runner: ^2.0.6

