name: mxc_logic
description: MXC shared logic library
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  chopper: ^4.0.1
  decimal: ^1.3.0

dev_dependencies:
  lint: ^1.5.3
  test: ^1.16.0
  
  chopper_generator: ^4.0.1
  json_annotation: ^4.0.1
  json_serializable: ^4.1.4
  swagger_dart_code_generator: 
    git: https://github.com/festelo/swagger-dart-code-generator.git
  build_runner: ^2.0.6

