name: mxc_ui
description: MXC UI Library
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  font_awesome_flutter: ^9.1.0
  provider: ^5.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^1.5.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 200
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 200
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 800

    - family: OpenSansEmoji
      fonts:
        - asset: assets/fonts/OpenSansEmoji.ttf

  assets:
    - assets/images/app/
    - assets/images/login/
    - assets/images/splash/
    - assets/images/home/
    - assets/images/deposit/
    - assets/images/withdraw/
    - assets/images/stake/
    - assets/images/wallet/
    - assets/images/device/
    - assets/images/gateway/
    - assets/images/calculator/currencies/
    - assets/images/connectivity/
    - assets/images/settings/
    - assets/images/maintenance/
    - assets/images/web/main_menu/
    - assets/images/web/nav/
    - assets/images/web/device/