name: mxc_ui
description: MXC UI Library
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  font_awesome_flutter: ^9.1.0
  provider: ^5.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^1.5.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/app/
    - assets/images/login/
    - assets/images/splash/
    - assets/images/home/
    - assets/images/deposit/
    - assets/images/withdraw/
    - assets/images/stake/
    - assets/images/wallet/
    - assets/images/device/
    - assets/images/gateway/
    - assets/images/calculator/currencies/
    - assets/images/connectivity/
    - assets/images/settings/
    - assets/images/maintenance/