name: mxc_ui
description: MXC UI Library
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  font_awesome_flutter: ^9.1.0
  provider: ^5.0.0
  flutter:
    sdk: flutter
  decimal: ^2.2.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
  assets:
    - assets/images/app/
    - assets/images/login/
    - assets/images/splash/
    - assets/images/home/
    - assets/images/deposit/
    - assets/images/withdraw/
    - assets/images/stake/
    - assets/images/wallet/
    - assets/images/device/
    - assets/images/gateway/
    - assets/images/calculator/currencies/
    - assets/images/connectivity/
    - assets/images/settings/
    - assets/images/maintenance/